Handle BG/FG edge cases
Kittl/vectorizing pull request #21
Opened 2023-05-12 17:30 UTC by big-nacho

2023-05-15 17:08 UTC, phil-r requested changes

2023-05-15 17:08 UTC, phil-r commented on src/process_binary.py
> +    if (foreground_area / pixel_count) < 0.001:
`0.001` is not one percent

2023-05-15 17:08 UTC, phil-r commented on src/process_binary.py
> +            # Then the inverted bitmap is better. And its area is at least 1.
1 what? pixel?

2023-05-15 17:40 UTC, big-nacho commented on src/process_binary.py
> +            # Then the inverted bitmap is better. And its area is at least 1.
Just 1. No unit applies here. These are just 1/0 bitmaps

2023-05-22 10:32 UTC, phil-r reviewed
lgtm

2023-05-22 10:32 UTC, phil-r approved these changes

2023-05-23 18:25 UTC, merged