Color support CU-861mthf3r
Kittl/vectorizing pull request #22
Opened 2023-06-13 21:26 UTC by big-nacho

2023-06-23 13:37 UTC, claas-c requested changes

2023-06-23 13:37 UTC, claas-c commented on src/server/server.py
> +            img = try_read_image_from_url(url)
lets log more infor about how long each step take:
* download
* solver (+ individual steps inside)
* upload

2023-06-26 13:29 UTC, big-nacho commented
@claas-c 
The last commit introduces time logs and some performance improvements:

1. Flattening code in `CubicBezier` was extracted from the class and rewritten to be able to be jit compiled with `numba`. After the first ever color request (since the functions are compiled at runtime), the difference in timing can be drastic. In general this technique could be used in many places and also there is the possibility to parallelize code, but both of these require heavy refactoring.

2. Quantizer no longer uses `MEDIANCUT`. It is generally fast but for some images it can take up to `15` seconds, and in those cases the whole thing would usually time out. Now an initial quantization is performed with `FASTOCTREE` method and `faiss` Kmeans is used to refine it. This was from a previous iteration and it produces good results too, it's just a lot faster.

3. Flattening threshold was increased from `.1` to `.2`. The difference doesn't seem noticeable but the performance improvements are.

2023-06-26 18:05 UTC, claas-c approved these changes
lgtm

2023-06-27 11:54 UTC, merged